### ISSUE TITLE
name_show and name_filter should fail by default if blockchain is incomplete

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecore#2]
Outdated name data is dangerous because it could include TLS fingerprints that were later revoked, or even the wrong owner of a name, both of which could be exploited to cause a MITM. It's also confusing to users because some websites will work fine, while others will be mysteriously broken.

I propose that name_show and name_filter return an error by default if the blockchain is incomplete (still downloading), or if errors were encountered (e.g. "you may need to upgrade"). An optional parameter (disabled by default) could enable name lookups regardless of this condition.

See https://github.com/namecoin/namecoin/issues/124 for history of this discussion.

**Comment by domob1812** [comment]
Agreed.  For completeness:  We should definitely also do this for `name_history` and `name_scan` (not sure why everyone always uses `name_filter` instead of the much faster `name_scan`).  What about the other commands, like `name_list` or `name_update`?  They should probably be handled in the same way as `sendtoaddress` of upstream Bitcoin.
Note that Bitcoin already has a toggle-able "safe mode", which we can use for this.  I'll look into the details and implement it "soon".

**Comment by domob1812** [comment]
https://github.com/namecoin/namecore/pull/3

**Comment by domob1812** [comment]
Done.
