### ISSUE TITLE
regtest listen on same port as bitcoind

### ISSUE THREAD

**Issue by ondrejsika** [namecoin/namecore#4]
i run bitcoind and namecoid in regtest mode and they have same default
connect port (18444).

i propose change namecoind default port to 18445 or 18555.

**Comment by cassiniNMC** [comment]
There are some more conflicting port numbers.
init.cpp, rpcnet.cpp, netbase_tests.cpp, chainparamsseeds.h, bitcoin-cli.cpp, chainparams.cpp and chainparamsbase.cpp contain one or more of these: 8332, 8333, 18332, 18333, 18334, 18336, 18444.

**Comment by domob1812** [comment]
Fixed.  I've changed the default regtest port to 18445 and updated the help texts that still contained the old ports.  `chainparamsseeds.h` is still not updated, since we need to decide on what nodes to actually hardcode there.  We could either use dedicated nodes run by community members or we could use a query from one of the DNS seeds (which is what Bitcoin does).
