### ISSUE TITLE
Feature request: sendtoname

### ISSUE THREAD

**Issue by cassiniNMC** [namecoin/namecore#5]
Currently this functionality can already be achieved by a combination of two RPCs (name_show and sendtoaddress). However, the sendtoname feature could become an important "unique selling proposition" in the future. Therefore sendtoname should be an RPC in its own right, I think.

**Comment by domob1812** [comment]
Please test: https://github.com/namecoin/namecore/pull/6

**Comment by JeremyRand** [comment]
I'm not really convinced that this is something we should encourage.  As I understand it (and please correct me if I'm wrong), using sendtoname will produce transactions that are easily linkable, both to each other and to the name.  While some users may intend for this information to be public (not really sure what use case it would be, maybe some kind of publicly auditable payment), the vast majority of users either will want it to be private or don't really care (but if they don't care, that usually means they just don't realize what linkability implies, and it should be private by default).

It seems to me that a better architecture would be to have the name's value include a payment address (which could be an ECDH address) and have the client send to that address.  If an ECDH address is used, then the payments will not be as easily linkable.

I realize that ECDH addresses are not well-standardized and are an area of active development.  But I do think that we should future-proof ourselves for widespread use of ECDH addresses (or other reusable addresses like zerocoin addresses), and sendtoname is incapable of this as far as I can tell.

**Comment by domob1812** [comment]
It is not a big feature and probably not something that a lot of people will use (as it is RPC-only), but it is still nice to have.  It is a feature we can trivially have in Namecoin, and which improves usability a lot compared to other coins - so much so that it would, basically, remove the need for both Onename and Netki.  That they got significant VC funding seems to imply that the feature is not so unimportant.

Of course, it has privacy implications - but so do addresses associated to id/.  Are you also in favour of removing them from the id/ spec and NameID?  I think it is nice to have for simplicity, and people who may use it must at least be familiar with the RPC interface (and know about the command in the first place) - so they can be expected to know what they are doing.

Are you definitely opposing merging this pull request, or is it ok for you nevertheless?

**Comment by JeremyRand** [comment]
Well, as I said, an id/ name can list an address that is safe to reuse (i.e. an ECDH address like DarkWallet and sx use).  That's not possible when using the script that corresponds to the owner of the name.  So I certainly support having id/ include payment addresses -- I'd just hope that users use ECDH addresses with them (or zerocoin addresses if those become a thing later).  Is there a disadvantage to using a payment address from the name's value rather than the name's owner script?  I realize that it would require parsing the JSON of the name's value, but this doesn't seem to outweight the privacy advantage of such an approach, in my opinion.  (And NMControl could easily do this; @phelixbtc and I were discussing doing so a while back.)

Unfortunately there are users who do surprisingly stupid things with RPC and/or command line tools, particularly when some third party writes a "n00b friendly howto guide" that doesn't disclose the privacy risks.  (I've been asked in the past to repair various bad things that novices did due to following bad howtos that they didn't understand, and I never cease being amazed at what damage can happen in such cases.)

I would like to get some further discussion before we decide on whether to support this API.

**Comment by phelixbtc** [comment]
There is no difference in privacy between sendtoname and having a normal address in the value. For now we simply don't have stealth addresses (of course that would be a feature great to have).

**Comment by JeremyRand** [comment]
The difference is that using the name value will future proof us for stealth addresses.  Stealth addresses should work fine on the Namecoin network right now, just no clients utilize them.  Is there a disadvantage to using the name value?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JeremyRand** [comment]
To elaborate now that I'm back at my laptop (was on my phone earlier) -- I'm against introducing features that will need to be deprecated in the near future.  While stealth addresses are not used by Namecoin users at the moment, they will be in the near future presumably.  Using the name value means that we will not have to adjust anything when stealth addresses (or zerocoin addresses) become supported.  It is impossible to support stealth addresses or zerocoin addresses by using the name's owner script (which is what sendtoname does).  There is no reason that I'm aware of to not use the name value.

**Comment by phelixbtc** [comment]
This is not about introducing a new feature. It has been present for a long time in the old client. We can not simply change it's behavior. We should introduce a new rpc command for using an address from the value, maybe specifically for stealth addresses.

**Comment by JeremyRand** [comment]
@phelixbtc It is true that this functionality has been in NamecoinQ for a while.  However, since we're pressuring end users to go to some effort to migrate to Namecoin Core anyway, it seems that the switch to Namecoin Core is a convenient time to remove that functionality.  If we don't remove it now, then I would support (at the least) marking it as dangerous in the documentation, and removing it in the future (let's say 6 months after NMControl merges support for using the JSON field for this functionality).  The fact that a little-known feature existed for some time, is not (by itself) a solid reason to keep it indefinitely IMO.

**Comment by cassiniNMC** [comment]
> then I would support (at the least) marking it as dangerous

If sendtoname is dangerous then Namecoin is dangerous. Or put it the other way around, if we remove sendtoname with the intention of improving privacy then this would lead to a false sense of safety. There is still sendtoaddress which is much more dangerous as it pretends to be anonymous.

**Comment by JeremyRand** [comment]
@cassiniNMC That isn't really the case.  sendtoaddress can (in principle) use ECDH addresses (e.g. stealth addresses), which are safe to reuse, and they can also (right now) use unique addresses if the user supplies them.  sendtoname, by its nature, cannot use ECDH addresses, nor can it use unique addresses.  Therefore sendtoname is substantially more dangerous than sendtoaddress.

**Comment by phelixbtc** [comment]
We can't randomly cripple functionality just with a vague hint that there might be something better coming up.

**Comment by JeremyRand** [comment]
@phelixbtc Fine.  I will propose deprecating/removing sendtoname from Namecoin Core approximately 6-12 months after both value-based sending and reusable addresses have been implemented in NMControl and wallets.  I will not NACK sendtoname until that has happened, since it is already in the NamecoinQ API and there is not a great alternative at the moment.  Is that okay?

**Comment by phelixbtc** [comment]
@JeremyRand Yep, sounds like a good plan.
